* TLS

it should initiate a connection to the server on the appropriate port and then send the TLS ClientHello to begin the TLS handshake.

when the TLS handshake has finished.

the client may then initiate the first HTTP request.

all HTTP data MUST be sent as TLS application data.

In general, HTTP/TLS requests are generated by dereferencing a URI.

if the hostname is available, the client MUST check it against the server's identity as presented in the server's Certificate message.

if a subjectAltName extension of type dNSName is present, that MUST be used as the identity.

otherwise, the Common Name field in the Subject field of the certificate MUST be used.

matching is performed using the matching rules specified by [RFC2459].

if the hostname does not match the identity in the certificate, user oriented clients MUST either notify the user or terminate the connection with a bad certificate error.

in order to prevent this form of attack, users should carefully examine the certificate presented by the server to determine if it meets their expections.
